---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-credentials
  namespace: grafana
type: Opaque
stringData:
  GF_SECURITY_ADMIN_USER: admin
  GF_SECURITY_ADMIN_PASSWORD: grafana123!
---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: "openshift-metrics"
spec:
  config:
    log:
      mode: console
    security:
      disable_initial_admin_creation: "false"
  deployment:
    spec:
      template:
        spec:
          automountServiceAccountToken: true
    secret:
      name: grafana-admin-credentials
  route:
    spec:
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect