apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: thanos-prometheus-ds
  namespace: grafana
spec:
  instanceSelector:
    matchLabels:
      dashboards: "openshift-metrics"
  datasource:
    name: Prometheus-Thanos-DS
    type: prometheus
    access: proxy
    url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
    jsonData:
      httpHeaderName1: 'Authorization'
      timeInterval: 15s
      tlsSkipVerify: true
    secureJsonData:
      httpHeaderValue1: 'Bearer <token>'
  resyncPeriod: 10m
